/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOVE = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int HOP = 10;
  /** RegularExpression Id. */
  int GO = 11;
  /** RegularExpression Id. */
  int ROBOT_R = 12;
  /** RegularExpression Id. */
  int VARS = 13;
  /** RegularExpression Id. */
  int PROCS = 14;
  /** RegularExpression Id. */
  int ASSIGNTO = 15;
  /** RegularExpression Id. */
  int GOTO = 16;
  /** RegularExpression Id. */
  int TURN = 17;
  /** RegularExpression Id. */
  int FACE = 18;
  /** RegularExpression Id. */
  int MOVETOTHE = 19;
  /** RegularExpression Id. */
  int MOVEINDIR = 20;
  /** RegularExpression Id. */
  int JUMPTOTHE = 21;
  /** RegularExpression Id. */
  int JUMPINDIR = 22;
  /** RegularExpression Id. */
  int NOP = 23;
  /** RegularExpression Id. */
  int IF = 24;
  /** RegularExpression Id. */
  int THEN = 25;
  /** RegularExpression Id. */
  int ELSE = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int DO = 28;
  /** RegularExpression Id. */
  int REPEAT = 29;
  /** RegularExpression Id. */
  int FACING = 30;
  /** RegularExpression Id. */
  int CANPUT = 31;
  /** RegularExpression Id. */
  int CANPICK = 32;
  /** RegularExpression Id. */
  int CANMOVEINDIR = 33;
  /** RegularExpression Id. */
  int CANJUMPINDIR = 34;
  /** RegularExpression Id. */
  int CANMOVETOTHE = 35;
  /** RegularExpression Id. */
  int CANJUMPTOTHE = 36;
  /** RegularExpression Id. */
  int NOT = 37;
  /** RegularExpression Id. */
  int FRONT = 38;
  /** RegularExpression Id. */
  int LEFT = 39;
  /** RegularExpression Id. */
  int BACK = 40;
  /** RegularExpression Id. */
  int AROUND = 41;
  /** RegularExpression Id. */
  int NORTH = 42;
  /** RegularExpression Id. */
  int SOUTH = 43;
  /** RegularExpression Id. */
  int EAST = 44;
  /** RegularExpression Id. */
  int WEST = 45;
  /** RegularExpression Id. */
  int NUM = 46;
  /** RegularExpression Id. */
  int CHIPS = 47;
  /** RegularExpression Id. */
  int BALLOONS = 48;
  /** RegularExpression Id. */
  int NAME = 49;
  /** RegularExpression Id. */
  int STR = 50;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"MOVE\"",
    "\"right\"",
    "\"PUT\"",
    "\"PICK\"",
    "\"POP\"",
    "\"HOP\"",
    "\"GO\"",
    "\"ROBOT_R\"",
    "\"VARS\"",
    "\"PROCS\"",
    "\"assignTo\"",
    "\"goto\"",
    "\"turn\"",
    "\"face\"",
    "\"moveToThe\"",
    "\"moveInDir\"",
    "\"jumpToThe\"",
    "\"jumpInDir\"",
    "\"nop\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"repeat\"",
    "\"facing\"",
    "\"canPut\"",
    "\"canPick\"",
    "\"canMoveInDir\"",
    "\"canJumpInDir\"",
    "\"canMoveToThe\"",
    "\"canJumpToThe\"",
    "\"not\"",
    "\"FRONT\"",
    "\"LEFT\"",
    "\"BACK\"",
    "\"AROUND\"",
    "\"NORTH\"",
    "\"SOUTH\"",
    "\"EAST\"",
    "\"WEST\"",
    "<NUM>",
    "\"CHIPS\"",
    "\"BALLOONS\"",
    "<NAME>",
    "<STR>",
    "\"(\"",
    "\");\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\"[\"",
    "\"]\"",
    "\"|\"",
  };

}
